language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm

install:
    - composer self-update
    - composer install --prefer-dist

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - ./vendor/bin/coveralls --verbose
    - bash <(curl -s https://codecov.io/bash)
    - ./vendor/bin/test-reporter
